# Default hyperparameters for environments not explicitly listed
default:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'

snake-v0:
  n_timesteps: !!float 3e6
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 250
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.2
  exploration_final_eps: 0.05
  policy_kwargs: "dict(net_arch=[256, 256])"

snake-image-v0:
  n_timesteps: !!float 1e6
  policy: 'CnnPolicy'
  policy_kwargs: "dict(features_extractor_class=importlib.import_module('cnn_features').CnnExtractor, features_extractor_kwargs=dict(features_dim=128), normalize_images=False)"
  learning_rate: !!float 1e-4
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 250
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.2
  exploration_final_eps: 0.05
